"""PKCE (Proof Key for Code Exchange) utilities for OAuth 2.0 authorization code flow.

This module provides functions to generate and verify PKCE challenge pairs:
- code_verifier: A cryptographically random string (43-128 characters)
- code_challenge: Base64URL-encoded SHA256 hash of the verifier (S256 method)
- state: A cryptographically random string to prevent CSRF attacks

PKCE helps prevent authorization code interception attacks by ensuring that the
client that initiates the authorization flow is the same client that completes it.
"""

import base64
import hashlib
import secrets
import re
from typing import Tuple


# PKCE parameters as per RFC 7636
CODE_VERIFIER_MIN_LENGTH = 43
CODE_VERIFIER_MAX_LENGTH = 128
CODE_VERIFIER_CHARSET = re.compile(r'^[A-Za-z0-9._~-]+$')


def generate_code_verifier(length: int = 128) -> str:
    """Generate a cryptographically secure code_verifier for PKCE.
    
    The code_verifier is a cryptographically random string using the
    unreserved characters [A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~",
    with between 43 and 128 characters.
    
    Args:
        length: Length of the code_verifier (default 128, max 128)
    
    Returns:
        A cryptographically secure code_verifier string
    
    Raises:
        ValueError: If length is not between 43 and 128
    """
    if length < CODE_VERIFIER_MIN_LENGTH or length > CODE_VERIFIER_MAX_LENGTH:
        raise ValueError(
            f"code_verifier length must be between {CODE_VERIFIER_MIN_LENGTH} "
            f"and {CODE_VERIFIER_MAX_LENGTH}, got {length}"
        )
    
    # Use secrets.token_urlsafe for cryptographically secure random bytes
    # that are URL-safe (uses unreserved characters)
    # Generate enough random bytes to get the desired length
    # Each byte gives ~1.33 characters in base64url encoding
    token_bytes = length * 3 // 4 + 1
    verifier = secrets.token_urlsafe(token_bytes)[:length]
    
    # Ensure the verifier only contains valid characters
    if not CODE_VERIFIER_CHARSET.match(verifier):
        # Fallback: generate manually with allowed characters
        allowed_chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~'
        verifier = ''.join(secrets.choice(allowed_chars) for _ in range(length))
    
    return verifier


def generate_code_challenge(code_verifier: str) -> str:
    """Generate a code_challenge from a code_verifier using S256 method.
    
    The S256 method computes the SHA256 hash of the code_verifier,
    then base64url-encodes it without padding.
    
    Args:
        code_verifier: The code_verifier string generated by generate_code_verifier
    
    Returns:
        The Base64URL-encoded SHA256 hash of the verifier
    
    Raises:
        ValueError: If code_verifier is invalid (wrong length or characters)
    """
    # Validate the code_verifier
    if not code_verifier:
        raise ValueError("code_verifier cannot be empty")
    
    if len(code_verifier) < CODE_VERIFIER_MIN_LENGTH or len(code_verifier) > CODE_VERIFIER_MAX_LENGTH:
        raise ValueError(
            f"code_verifier must be between {CODE_VERIFIER_MIN_LENGTH} "
            f"and {CODE_VERIFIER_MAX_LENGTH} characters"
        )
    
    if not CODE_VERIFIER_CHARSET.match(code_verifier):
        raise ValueError(
            "code_verifier contains invalid characters. "
            "Must use only [A-Z] / [a-z] / [0-9] / '-' / '.' / '_' / '~'"
        )
    
    # Compute SHA256 hash
    digest = hashlib.sha256(code_verifier.encode('ascii')).digest()
    
    # Base64URL encode without padding (RFC 7636 specifies no padding)
    challenge = base64.urlsafe_b64encode(digest).decode('ascii').rstrip('=')
    
    return challenge


def generate_state(length: int = 32) -> str:
    """Generate a cryptographically secure state parameter.
    
    The state parameter is used to prevent CSRF attacks by ensuring
    that the callback is from the same authorization request that
    was initiated.
    
    Args:
        length: Length of the state string (default 32)
    
    Returns:
        A cryptographically secure state string
    """
    if length < 16:
        raise ValueError("state length must be at least 16 characters")
    
    # Use secrets.token_urlsafe for URL-safe random string
    token_bytes = length * 3 // 4 + 1
    state = secrets.token_urlsafe(token_bytes)[:length]
    
    return state


def verify_code_verifier(code_verifier: str, code_challenge: str) -> bool:
    """Verify that a code_verifier matches a code_challenge.
    
    This is used during the token exchange phase to ensure the
    client that requested the authorization is the same client
    that is exchanging the code.
    
    Args:
        code_verifier: The code_verifier to verify
        code_challenge: The expected code_challenge
    
    Returns:
        True if the verifier matches the challenge, False otherwise
    """
    try:
        computed_challenge = generate_code_challenge(code_verifier)
        return computed_challenge == code_challenge
    except ValueError:
        return False


def generate_pkce_pair(length: int = 128) -> Tuple[str, str]:
    """Generate a complete PKCE code_verifier and code_challenge pair.
    
    This is a convenience function that generates both the verifier
    and challenge in one call, ensuring they are correctly paired.
    
    Args:
        length: Length of the code_verifier (default 128)
    
    Returns:
        A tuple of (code_verifier, code_challenge)
    """
    verifier = generate_code_verifier(length)
    challenge = generate_code_challenge(verifier)
    return verifier, challenge
